defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"

exclude:
- README.md
- Gemfile
- Gemfile.lock
- _setup.sh
- new_post.sh
- new_post.pl

name: JACK Audio Connection Kit
markdown: Kramdown
highlighter: rouge
baseurl: ''
